#!/usr/bin/env bash
# comm(1) in the guest.
#
# Every expected value below is what GNU comm prints for the same input and
# command; they were generated by running the system tool rather than written
# by hand, because a hand-written expectation is how a case starts lying.
#
# Expectations that contain a tab are written with printf, so the column
# separators are visible in the source instead of hiding as whitespace.
set -u

fail() { echo "FAIL: $*" >&2; exit 1; }
check() {
  if [ "$2" != "$3" ]; then
    printf 'FAIL: %s\n  expected: [%s]\n  actual:   [%s]\n' "$1" "$2" "$3" >&2
    exit 1
  fi
}

W=/tmp/comm-case
rm -rf "$W"
mkdir -p "$W"

printf '%s\n' a b c d e > "$W/f1"
printf '%s\n' b c d f > "$W/f2"
printf '%s\n' a b c > "$W/same"
printf '%s\n' a b c > "$W/sorted"
printf '%s\n' b a c > "$W/unsorted"
printf 'a b\nb\n' > "$W/prefix"
printf '%s\n' a > "$W/one"
printf '%s\n' b a > "$W/two"

# --- the three columns ----------------------------------------------------
# A line in both files carries a separator for each earlier column, so the
# third column is indented by two tabs and the second by one.
check "comm default" "$(printf 'a\n\t\tb\n\t\tc\n\t\td\ne\n\tf')" \
  "$(comm "$W/f1" "$W/f2")"

# Suppressing a column takes its separator with it.
check "comm -1" "$(printf '\tb\n\tc\n\td\nf')" "$(comm -1 "$W/f1" "$W/f2")"
check "comm -2" "$(printf 'a\n\tb\n\tc\n\td\ne')" "$(comm -2 "$W/f1" "$W/f2")"
check "comm -3" "$(printf 'a\ne\n\tf')" "$(comm -3 "$W/f1" "$W/f2")"
check "comm -12" "$(printf 'b\nc\nd')" "$(comm -12 "$W/f1" "$W/f2")"
check "comm -123" '' "$(comm -123 "$W/f1" "$W/f2")"
check "comm identical files" "$(printf '\t\ta\n\t\tb\n\t\tc')" \
  "$(comm "$W/same" "$W/same")"

# The comparison is memcmp2, so a prefix sorts first.
check "comm prefix" "$(printf 'a b\n\t\tb\n\tc\n\td\n\tf')" \
  "$(comm "$W/prefix" "$W/f2")"

# --- --total --------------------------------------------------------------
# The summary counts all three columns whatever was suppressed.
check "comm --total" "$(printf 'a\n\t\tb\n\t\tc\n\t\td\ne\n\tf\n2\t1\t3\ttotal')" \
  "$(comm --total "$W/f1" "$W/f2")"
check "comm --total -1" "$(printf '\tb\n\tc\n\td\nf\n2\t1\t3\ttotal')" \
  "$(comm --total -1 "$W/f1" "$W/f2")"
check "comm --total identical" "$(printf '\t\ta\n\t\tb\n\t\tc\n0\t0\t3\ttotal')" \
  "$(comm --total "$W/same" "$W/same")"

# --- --output-delimiter ---------------------------------------------------
check "comm one delimiter" "$(printf 'a\n,,b\n,,c\n,,d\ne\n,f')" \
  "$(comm --output-delimiter=, "$W/f1" "$W/f2")"
check "comm multi delimiter" "$(printf 'a\n |  | b\n |  | c\n |  | d\ne\n | f')" \
  "$(comm --output-delimiter=' | ' "$W/f1" "$W/f2")"

# --- operands -------------------------------------------------------------
check "comm stdin" "$(printf 'a\n\t\tb\n\t\tc\n\t\td\ne\n\tf')" \
  "$(comm - "$W/f2" < "$W/f1")"

# --- the order check ------------------------------------------------------
# By default a disorder is a warning: the comparison still runs to the end and
# the exit status is 1.
if comm "$W/unsorted" "$W/sorted" >/dev/null 2>&1; then
  fail "comm with unsorted input succeeded"
fi
check "comm unsorted output" "$(printf '\ta\n\t\tb\na\n\t\tc')" \
  "$(comm "$W/unsorted" "$W/sorted")"
check "comm unsorted message" 'comm: file 1 is not in sorted order
comm: input is not in sorted order' \
  "$(comm "$W/unsorted" "$W/sorted" 2>&1 >/dev/null)"
check "comm unsorted still totals" "$(printf '\ta\n\t\tb\na\n\t\tc\n1\t1\t2\ttotal')" \
  "$(comm --total "$W/unsorted" "$W/sorted")"

# The check only runs once a line has failed to pair up. "b" then "a" is out of
# order, but "b" matched on the first row, so nothing was unpairable yet and the
# default run says nothing at all.
if comm "$W/f1" "$W/f2" >/dev/null 2>&1; then
  check "comm sorted exit" 0 0
else
  fail "comm with sorted input exited non-zero"
fi
check "comm sorted is quiet" '' "$(comm "$W/f1" "$W/f2" 2>&1 >/dev/null)"

# --nocheck-order keeps the output and drops both the complaint and the
# non-zero status.
if comm --nocheck-order "$W/unsorted" "$W/sorted" >/dev/null 2>&1; then
  check "comm --nocheck-order exit" 0 0
else
  fail "comm --nocheck-order exited non-zero"
fi
check "comm --nocheck-order output" "$(printf '\ta\n\t\tb\na\n\t\tc')" \
  "$(comm --nocheck-order "$W/unsorted" "$W/sorted")"
check "comm --nocheck-order is quiet" '' \
  "$(comm --nocheck-order "$W/unsorted" "$W/sorted" 2>&1 >/dev/null)"

# --check-order is fatal on the first complaint: no closing message, no
# summary, and the comparison stops there.
if comm --check-order "$W/unsorted" "$W/sorted" >/dev/null 2>&1; then
  fail "comm --check-order succeeded"
fi
check "comm --check-order stops early" "$(printf '\ta\n\t\tb')" \
  "$(comm --check-order "$W/unsorted" "$W/sorted")"
check "comm --check-order message" 'comm: file 1 is not in sorted order' \
  "$(comm --check-order "$W/unsorted" "$W/sorted" 2>&1 >/dev/null)"
# --check-order dies before the summary, so the total line is never written even
# though the lines it managed to compare were.
check "comm --check-order has no total" "$(printf '\ta\n\t\tb')" \
  "$(comm --check-order --total "$W/unsorted" "$W/sorted" 2>/dev/null)"
# The fatal run reports the file and stops; it never adds the closing complaint.
check "comm --check-order has no closing complaint" 'comm: file 1 is not in sorted order' \
  "$(comm --check-order --total "$W/unsorted" "$W/sorted" 2>&1 >/dev/null)"

# The second file can be the disordered one, and it is named file 2.
if comm "$W/one" "$W/two" >/dev/null 2>&1; then
  fail "comm with an unsorted second file succeeded"
fi
check "comm second file disorder" "$(printf 'a\n\tb\n\ta')" \
  "$(comm "$W/one" "$W/two")"
check "comm second file message" 'comm: file 2 is not in sorted order
comm: input is not in sorted order' \
  "$(comm "$W/one" "$W/two" 2>&1 >/dev/null)"

# --- diagnostics ----------------------------------------------------------
if comm "$W/nope" "$W/f2" >/dev/null 2>&1; then
  fail "comm with a missing file succeeded"
fi
check "comm missing file" "comm: $W/nope: No such file or directory" \
  "$(comm "$W/nope" "$W/f2" 2>&1 >/dev/null)"

if comm "$W/f1" >/dev/null 2>&1; then
  fail "comm with one operand succeeded"
fi
# An operand is quoted with typographic quotes, unlike a file name.
check "comm missing operand" "comm: missing operand after ‘$W/f1’
Try 'comm --help' for more information." "$(comm "$W/f1" 2>&1 >/dev/null)"

if comm >/dev/null 2>&1; then
  fail "comm with no operands succeeded"
fi
check "comm no operands" 'comm: missing operand
Try '"'"'comm --help'"'"' for more information.' "$(comm 2>&1 >/dev/null)"

if comm "$W/f1" "$W/f2" "$W/f1" >/dev/null 2>&1; then
  fail "comm with three operands succeeded"
fi
check "comm extra operand" "comm: extra operand ‘$W/f1’
Try 'comm --help' for more information." \
  "$(comm "$W/f1" "$W/f2" "$W/f1" 2>&1 >/dev/null)"

if comm -Q "$W/f1" "$W/f2" >/dev/null 2>&1; then
  fail "comm -Q succeeded"
fi
check "comm bad option" "comm: invalid option -- 'Q'
Try 'comm --help' for more information." "$(comm -Q "$W/f1" "$W/f2" 2>&1 >/dev/null)"

if comm "$W/f1" "$W/f2" --output-delimiter >/dev/null 2>&1; then
  fail "comm --output-delimiter with no argument succeeded"
fi
check "comm missing delimiter argument" "comm: option '--output-delimiter' requires an argument
Try 'comm --help' for more information." \
  "$(comm "$W/f1" "$W/f2" --output-delimiter 2>&1 >/dev/null)"

if comm --output-delimiter=, --output-delimiter=X "$W/f1" "$W/f2" >/dev/null 2>&1; then
  fail "comm with two different delimiters succeeded"
fi
check "comm two delimiters" 'comm: multiple output delimiters specified' \
  "$(comm --output-delimiter=, --output-delimiter=X "$W/f1" "$W/f2" 2>&1 >/dev/null)"

rm -rf "$W"
echo "comm ok"
exit 0