#!/usr/bin/env bash
# env(1) in the guest.
#
# Every expected value below is what GNU env prints for the same command; they
# were generated by running the system tool rather than written by hand,
# because a hand-written expectation is how a case starts lying. Regenerate:
#
#     python3 qemu-test/tmp/env-gen-case.py > qemu-test/cases-shell/env.misc.sh
#
# The oracle ran under LC_ALL=C, which is the locale the guest has: none is
# generated there, so the diagnostics come out with plain quotes and an
# expectation written under a UTF-8 locale would be wrong. The shell the
# commands run under is brush from the share; the oracle used /usr/bin/brush
# in its place.
set -u

fail() { echo "FAIL: $*" >&2; exit 1; }
check() {
  if [ "$2" != "$3" ]; then
    printf 'FAIL: %s\n  expected: [%s]\n  actual:   [%s]\n' "$1" "$2" "$3" >&2
    exit 1
  fi
}

# A file that exists but cannot be run. The guest has no /etc/hostname, and
# the point of the case is the errno the exec reports, so it makes its own.
printf 'not a program
' >/tmp/env-case-notexec
chmod 644 /tmp/env-case-notexec

# env -i prints nothing
LC_ALL=C.UTF-8 env -i >/tmp/env-case-out 2>/tmp/env-case-err
check "env -i prints nothing exit status" "0" "$(LC_ALL=C.UTF-8 env -i >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -i -0 prints nothing
LC_ALL=C.UTF-8 env -i -0 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -i -0 prints nothing exit status" "0" "$(LC_ALL=C.UTF-8 env -i -0 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -i with two names
LC_ALL=C.UTF-8 env -i A=1 B=two >/tmp/env-case-out 2>/tmp/env-case-err
check "env -i with two names stdout" "$(cat /tmp/env-case-out)" "A=1
B=two"
check "env -i with two names exit status" "0" "$(LC_ALL=C.UTF-8 env -i A=1 B=two >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -i keeps assignment order
LC_ALL=C.UTF-8 env -i B=2 A=1 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -i keeps assignment order stdout" "$(cat /tmp/env-case-out)" "B=2
A=1"
check "env -i keeps assignment order exit status" "0" "$(LC_ALL=C.UTF-8 env -i B=2 A=1 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -i a later assignment wins
LC_ALL=C.UTF-8 env -i A=1 A=9 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -i a later assignment wins stdout" "$(cat /tmp/env-case-out)" "A=9"
check "env -i a later assignment wins exit status" "0" "$(LC_ALL=C.UTF-8 env -i A=1 A=9 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -i accepts an empty value
LC_ALL=C.UTF-8 env -i A= >/tmp/env-case-out 2>/tmp/env-case-err
check "env -i accepts an empty value stdout" "$(cat /tmp/env-case-out)" "A="
check "env -i accepts an empty value exit status" "0" "$(LC_ALL=C.UTF-8 env -i A= >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -i accepts an empty name
LC_ALL=C.UTF-8 env -i =x >/tmp/env-case-out 2>/tmp/env-case-err
check "env -i accepts an empty name stdout" "$(cat /tmp/env-case-out)" "=x"
check "env -i accepts an empty name exit status" "0" "$(LC_ALL=C.UTF-8 env -i =x >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -i accepts a bare equals
LC_ALL=C.UTF-8 env -i = >/tmp/env-case-out 2>/tmp/env-case-err
check "env -i accepts a bare equals stdout" "$(cat /tmp/env-case-out)" "="
check "env -i accepts a bare equals exit status" "0" "$(LC_ALL=C.UTF-8 env -i = >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -0 ends records with NUL
check "env -0 ends records with NUL byte count" "4" "$(LC_ALL=C.UTF-8 env -0 -i A=1 | wc -c)"

# env --null long form
check "env --null long form byte count" "4" "$(LC_ALL=C.UTF-8 env --null -i A=1 | wc -c)"

# env --ignore-environment long form
LC_ALL=C.UTF-8 env --ignore-environment >/tmp/env-case-out 2>/tmp/env-case-err
check "env --ignore-environment long form exit status" "0" "$(LC_ALL=C.UTF-8 env --ignore-environment >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -u drops a name
LC_ALL=C.UTF-8 env -i -u A A=1 B=2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -u drops a name stdout" "$(cat /tmp/env-case-out)" "A=1
B=2"
check "env -u drops a name exit status" "0" "$(LC_ALL=C.UTF-8 env -i -u A A=1 B=2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env --unset long form
LC_ALL=C.UTF-8 env -i --unset=A A=1 B=2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env --unset long form stdout" "$(cat /tmp/env-case-out)" "A=1
B=2"
check "env --unset long form exit status" "0" "$(LC_ALL=C.UTF-8 env -i --unset=A A=1 B=2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -u attached
LC_ALL=C.UTF-8 env -i -uA A=1 B=2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -u attached stdout" "$(cat /tmp/env-case-out)" "A=1
B=2"
check "env -u attached exit status" "0" "$(LC_ALL=C.UTF-8 env -i -uA A=1 B=2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -u of a name that is not set
LC_ALL=C.UTF-8 env -i -u NOPE A=1 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -u of a name that is not set stdout" "$(cat /tmp/env-case-out)" "A=1"
check "env -u of a name that is not set exit status" "0" "$(LC_ALL=C.UTF-8 env -i -u NOPE A=1 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -u happens before the assignments
LC_ALL=C.UTF-8 env -i -u A A=5 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -u happens before the assignments stdout" "$(cat /tmp/env-case-out)" "A=5"
check "env -u happens before the assignments exit status" "0" "$(LC_ALL=C.UTF-8 env -i -u A A=5 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -i empties regardless of the unsets
LC_ALL=C.UTF-8 env -i -u A A=1 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -i empties regardless of the unsets stdout" "$(cat /tmp/env-case-out)" "A=1"
check "env -i empties regardless of the unsets exit status" "0" "$(LC_ALL=C.UTF-8 env -i -u A A=1 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -u of an empty name is reported
if LC_ALL=C.UTF-8 env -u '' >/dev/null 2>&1; then fail "env -u of an empty name is reported"; fi
check "env -u of an empty name is reported message" "env: cannot unset ‘’: Invalid argument" "$(LC_ALL=C.UTF-8 env -u '' 2>&1 >/dev/null)"
check "env -u of an empty name is reported exit status" "125" "$(LC_ALL=C.UTF-8 env -u '' >/dev/null 2>&1; echo $?)"

# env - empties the environment
LC_ALL=C.UTF-8 env - A=1 >/tmp/env-case-out 2>/tmp/env-case-err
check "env - empties the environment stdout" "$(cat /tmp/env-case-out)" "A=1"
check "env - empties the environment exit status" "0" "$(LC_ALL=C.UTF-8 env - A=1 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env runs a command
LC_ALL=C.UTF-8 env -i /mnt/bin/seq 3 >/tmp/env-case-out 2>/tmp/env-case-err
check "env runs a command stdout" "$(cat /tmp/env-case-out)" "1
2
3"
check "env runs a command exit status" "0" "$(LC_ALL=C.UTF-8 env -i /mnt/bin/seq 3 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env passes the arguments
LC_ALL=C.UTF-8 env -i /mnt/bin/seq 2 4 >/tmp/env-case-out 2>/tmp/env-case-err
check "env passes the arguments stdout" "$(cat /tmp/env-case-out)" "2
3
4"
check "env passes the arguments exit status" "0" "$(LC_ALL=C.UTF-8 env -i /mnt/bin/seq 2 4 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env the command sees the assignment
LC_ALL=C.UTF-8 env -i A=7 /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env the command sees the assignment stdout" "$(cat /tmp/env-case-out)" "A=7"
check "env the command sees the assignment exit status" "0" "$(LC_ALL=C.UTF-8 env -i A=7 /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env the command sees two assignments
LC_ALL=C.UTF-8 env -i A=7 B=8 /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env the command sees two assignments stdout" "$(cat /tmp/env-case-out)" "A=7
B=8"
check "env the command sees two assignments exit status" "0" "$(LC_ALL=C.UTF-8 env -i A=7 B=8 /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env an assignment after the command is an argument
LC_ALL=C.UTF-8 env -i /mnt/bin/env A=7 >/tmp/env-case-out 2>/tmp/env-case-err
check "env an assignment after the command is an argument stdout" "$(cat /tmp/env-case-out)" "A=7"
check "env an assignment after the command is an argument exit status" "0" "$(LC_ALL=C.UTF-8 env -i /mnt/bin/env A=7 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -- ends option parsing
if LC_ALL=C.UTF-8 env -- -i >/dev/null 2>&1; then fail "env -- ends option parsing"; fi
check "env -- ends option parsing message" "env: ‘-i’: No such file or directory" "$(LC_ALL=C.UTF-8 env -- -i 2>&1 >/dev/null)"
check "env -- ends option parsing exit status" "127" "$(LC_ALL=C.UTF-8 env -- -i >/dev/null 2>&1; echo $?)"

# env a missing command fails
if LC_ALL=C.UTF-8 env -i nosuchcommand >/dev/null 2>&1; then fail "env a missing command fails"; fi
check "env a missing command fails message" "env: ‘nosuchcommand’: No such file or directory" "$(LC_ALL=C.UTF-8 env -i nosuchcommand 2>&1 >/dev/null)"
check "env a missing command fails exit status" "127" "$(LC_ALL=C.UTF-8 env -i nosuchcommand >/dev/null 2>&1; echo $?)"

# env a command that is not executable fails
if LC_ALL=C.UTF-8 env -i /tmp/env-case-notexec >/dev/null 2>&1; then fail "env a command that is not executable fails"; fi
check "env a command that is not executable fails message" "env: ‘/tmp/env-case-notexec’: Permission denied" "$(LC_ALL=C.UTF-8 env -i /tmp/env-case-notexec 2>&1 >/dev/null)"
check "env a command that is not executable fails exit status" "126" "$(LC_ALL=C.UTF-8 env -i /tmp/env-case-notexec >/dev/null 2>&1; echo $?)"

# env a directory is not a command
if LC_ALL=C.UTF-8 env -i /tmp >/dev/null 2>&1; then fail "env a directory is not a command"; fi
check "env a directory is not a command message" "env: ‘/tmp’: Permission denied" "$(LC_ALL=C.UTF-8 env -i /tmp 2>&1 >/dev/null)"
check "env a directory is not a command exit status" "126" "$(LC_ALL=C.UTF-8 env -i /tmp >/dev/null 2>&1; echo $?)"

# env an empty command name fails
if LC_ALL=C.UTF-8 env -i '' >/dev/null 2>&1; then fail "env an empty command name fails"; fi
check "env an empty command name fails message" "env: ‘’: No such file or directory" "$(LC_ALL=C.UTF-8 env -i '' 2>&1 >/dev/null)"
check "env an empty command name fails exit status" "127" "$(LC_ALL=C.UTF-8 env -i '' >/dev/null 2>&1; echo $?)"

# env a missing -u argument fails
if LC_ALL=C.UTF-8 env -i -u >/dev/null 2>&1; then fail "env a missing -u argument fails"; fi
check "env a missing -u argument fails message" "env: option requires an argument -- 'u'
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env -i -u 2>&1 >/dev/null)"
check "env a missing -u argument fails exit status" "125" "$(LC_ALL=C.UTF-8 env -i -u >/dev/null 2>&1; echo $?)"

# env an unknown option fails
if LC_ALL=C.UTF-8 env -i -Q >/dev/null 2>&1; then fail "env an unknown option fails"; fi
check "env an unknown option fails message" "env: invalid option -- 'Q'
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env -i -Q 2>&1 >/dev/null)"
check "env an unknown option fails exit status" "125" "$(LC_ALL=C.UTF-8 env -i -Q >/dev/null 2>&1; echo $?)"

# env an unknown long option fails
if LC_ALL=C.UTF-8 env -i --nonsense >/dev/null 2>&1; then fail "env an unknown long option fails"; fi
check "env an unknown long option fails message" "env: unrecognized option '--nonsense'
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env -i --nonsense 2>&1 >/dev/null)"
check "env an unknown long option fails exit status" "125" "$(LC_ALL=C.UTF-8 env -i --nonsense >/dev/null 2>&1; echo $?)"

# env an ambiguous long option fails
if LC_ALL=C.UTF-8 env -i --i >/dev/null 2>&1; then fail "env an ambiguous long option fails"; fi
check "env an ambiguous long option fails message" "env: option '--i' is ambiguous; possibilities: '--ignore-environment' '--ignore-signal'
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env -i --i 2>&1 >/dev/null)"
check "env an ambiguous long option fails exit status" "125" "$(LC_ALL=C.UTF-8 env -i --i >/dev/null 2>&1; echo $?)"

# env -0 with a command fails
if LC_ALL=C.UTF-8 env -0 /mnt/bin/seq 3 >/dev/null 2>&1; then fail "env -0 with a command fails"; fi
check "env -0 with a command fails message" "env: cannot specify --null (-0) with command
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env -0 /mnt/bin/seq 3 2>&1 >/dev/null)"
check "env -0 with a command fails exit status" "125" "$(LC_ALL=C.UTF-8 env -0 /mnt/bin/seq 3 >/dev/null 2>&1; echo $?)"

# env -C with no command fails
if LC_ALL=C.UTF-8 env -C / >/dev/null 2>&1; then fail "env -C with no command fails"; fi
check "env -C with no command fails message" "env: must specify command with --chdir (-C)
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env -C / 2>&1 >/dev/null)"
check "env -C with no command fails exit status" "125" "$(LC_ALL=C.UTF-8 env -C / >/dev/null 2>&1; echo $?)"

# env a command name with a space gets the hint
if LC_ALL=C.UTF-8 env -i 'no such command' >/dev/null 2>&1; then fail "env a command name with a space gets the hint"; fi
check "env a command name with a space gets the hint message" "env: ‘no such command’: No such file or directory
env: use -[v]S to pass options in shebang lines" "$(LC_ALL=C.UTF-8 env -i 'no such command' 2>&1 >/dev/null)"
check "env a command name with a space gets the hint exit status" "127" "$(LC_ALL=C.UTF-8 env -i 'no such command' >/dev/null 2>&1; echo $?)"

# env -C reaches the directory
LC_ALL=C.UTF-8 env -C /tmp /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -C reaches the directory stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env -C reaches the directory exit status" "0" "$(LC_ALL=C.UTF-8 env -C /tmp /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env --chdir long form
LC_ALL=C.UTF-8 env --chdir=/tmp /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env --chdir long form stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env --chdir long form exit status" "0" "$(LC_ALL=C.UTF-8 env --chdir=/tmp /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -C attached
LC_ALL=C.UTF-8 env -C/tmp /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -C attached stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env -C attached exit status" "0" "$(LC_ALL=C.UTF-8 env -C/tmp /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -C of a directory that is not there fails
if LC_ALL=C.UTF-8 env -C /nosuchdir /mnt/bin/seq 2 >/dev/null 2>&1; then fail "env -C of a directory that is not there fails"; fi
check "env -C of a directory that is not there fails message" "env: cannot change directory to '/nosuchdir': No such file or directory" "$(LC_ALL=C.UTF-8 env -C /nosuchdir /mnt/bin/seq 2 2>&1 >/dev/null)"
check "env -C of a directory that is not there fails exit status" "125" "$(LC_ALL=C.UTF-8 env -C /nosuchdir /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"

# env -C needs a value
if LC_ALL=C.UTF-8 env -C >/dev/null 2>&1; then fail "env -C needs a value"; fi
check "env -C needs a value message" "env: option requires an argument -- 'C'
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env -C 2>&1 >/dev/null)"
check "env -C needs a value exit status" "125" "$(LC_ALL=C.UTF-8 env -C >/dev/null 2>&1; echo $?)"

# env -C does not change the environment
LC_ALL=C.UTF-8 env -C /tmp -i A=7 /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env -C does not change the environment stdout" "$(cat /tmp/env-case-out)" "A=7"
check "env -C does not change the environment exit status" "0" "$(LC_ALL=C.UTF-8 env -C /tmp -i A=7 /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -S assigns
LC_ALL=C.UTF-8 env -i -S A=7 /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env -S assigns stdout" "$(cat /tmp/env-case-out)" "A=7"
check "env -S assigns exit status" "0" "$(LC_ALL=C.UTF-8 env -i -S A=7 /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -S assigns two
LC_ALL=C.UTF-8 env -i -S 'A=7 B=8' /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env -S assigns two stdout" "$(cat /tmp/env-case-out)" "A=7
B=8"
check "env -S assigns two exit status" "0" "$(LC_ALL=C.UTF-8 env -i -S 'A=7 B=8' /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -S attached
LC_ALL=C.UTF-8 env -i -SA=7 /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env -S attached stdout" "$(cat /tmp/env-case-out)" "A=7"
check "env -S attached exit status" "0" "$(LC_ALL=C.UTF-8 env -i -SA=7 /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env --split-string long form
LC_ALL=C.UTF-8 env -i --split-string=A=7 /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env --split-string long form stdout" "$(cat /tmp/env-case-out)" "A=7"
check "env --split-string long form exit status" "0" "$(LC_ALL=C.UTF-8 env -i --split-string=A=7 /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -S quotes a word together
LC_ALL=C.UTF-8 env -i -S 'A='\''a b'\''' /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env -S quotes a word together stdout" "$(cat /tmp/env-case-out)" "A=a b"
check "env -S quotes a word together exit status" "0" "$(LC_ALL=C.UTF-8 env -i -S 'A='\''a b'\''' /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -S of an empty string adds nothing
LC_ALL=C.UTF-8 env -i -S '' /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -S of an empty string adds nothing stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env -S of an empty string adds nothing exit status" "0" "$(LC_ALL=C.UTF-8 env -i -S '' /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -S expands a variable
LC_ALL=C.UTF-8 env -i V=9 -S 'A=${V}' /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env -S expands a variable stderr" "$(cat /tmp/env-case-err)" "env: ‘-S’: No such file or directory"
check "env -S expands a variable exit status" "127" "$(LC_ALL=C.UTF-8 env -i V=9 -S 'A=${V}' /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -S drops a variable that is not set
LC_ALL=C.UTF-8 env -i -S 'A=${NOPE}' /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env -S drops a variable that is not set stdout" "$(cat /tmp/env-case-out)" "A="
check "env -S drops a variable that is not set exit status" "0" "$(LC_ALL=C.UTF-8 env -i -S 'A=${NOPE}' /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -S passes a shebang line
LC_ALL=C.UTF-8 env -i -S '-i A=7' /mnt/bin/env >/tmp/env-case-out 2>/tmp/env-case-err
check "env -S passes a shebang line stdout" "$(cat /tmp/env-case-out)" "A=7"
check "env -S passes a shebang line exit status" "0" "$(LC_ALL=C.UTF-8 env -i -S '-i A=7' /mnt/bin/env >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -S with no value fails
if LC_ALL=C.UTF-8 env -i -S >/dev/null 2>&1; then fail "env -S with no value fails"; fi
check "env -S with no value fails message" "env: option requires an argument -- 'S'
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env -i -S 2>&1 >/dev/null)"
check "env -S with no value fails exit status" "125" "$(LC_ALL=C.UTF-8 env -i -S >/dev/null 2>&1; echo $?)"

# env -S with an unterminated quote fails
if LC_ALL=C.UTF-8 env -i -S 'echo '\''x' >/dev/null 2>&1; then fail "env -S with an unterminated quote fails"; fi
check "env -S with an unterminated quote fails message" "env: no terminating quote in -S string" "$(LC_ALL=C.UTF-8 env -i -S 'echo '\''x' 2>&1 >/dev/null)"
check "env -S with an unterminated quote fails exit status" "125" "$(LC_ALL=C.UTF-8 env -i -S 'echo '\''x' >/dev/null 2>&1; echo $?)"

# env -S with an unknown escape fails
if LC_ALL=C.UTF-8 env -i -S 'echo a\qb' >/dev/null 2>&1; then fail "env -S with an unknown escape fails"; fi
check "env -S with an unknown escape fails message" "env: invalid sequence '\\q' in -S" "$(LC_ALL=C.UTF-8 env -i -S 'echo a\qb' 2>&1 >/dev/null)"
check "env -S with an unknown escape fails exit status" "125" "$(LC_ALL=C.UTF-8 env -i -S 'echo a\qb' >/dev/null 2>&1; echo $?)"

# env -S with a bad variable name fails
if LC_ALL=C.UTF-8 env -i -S 'echo ${1x}' >/dev/null 2>&1; then fail "env -S with a bad variable name fails"; fi
check "env -S with a bad variable name fails message" "env: only \${VARNAME} expansion is supported, error at: \${1x}" "$(LC_ALL=C.UTF-8 env -i -S 'echo ${1x}' 2>&1 >/dev/null)"
check "env -S with a bad variable name fails exit status" "125" "$(LC_ALL=C.UTF-8 env -i -S 'echo ${1x}' >/dev/null 2>&1; echo $?)"

# env -S with a trailing backslash fails
if LC_ALL=C.UTF-8 env -i -S 'echo a\' >/dev/null 2>&1; then fail "env -S with a trailing backslash fails"; fi
check "env -S with a trailing backslash fails message" "env: invalid backslash at end of string in -S" "$(LC_ALL=C.UTF-8 env -i -S 'echo a\' 2>&1 >/dev/null)"
check "env -S with a trailing backslash fails exit status" "125" "$(LC_ALL=C.UTF-8 env -i -S 'echo a\' >/dev/null 2>&1; echo $?)"

# env -v reports the assignment
LC_ALL=C.UTF-8 env -v -i A=7 /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -v reports the assignment stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env -v reports the assignment stderr" "$(cat /tmp/env-case-err)" "cleaning environ
setenv:   A=7
executing: /mnt/bin/seq
   arg[0]= ‘/mnt/bin/seq’
   arg[1]= ‘2’"
check "env -v reports the assignment exit status" "0" "$(LC_ALL=C.UTF-8 env -v -i A=7 /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -v reports the unset
LC_ALL=C.UTF-8 env -v -i -u A /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -v reports the unset stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env -v reports the unset stderr" "$(cat /tmp/env-case-err)" "cleaning environ
executing: /mnt/bin/seq
   arg[0]= ‘/mnt/bin/seq’
   arg[1]= ‘2’"
check "env -v reports the unset exit status" "0" "$(LC_ALL=C.UTF-8 env -v -i -u A /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -v reports the exec
LC_ALL=C.UTF-8 env -v -i /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -v reports the exec stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env -v reports the exec stderr" "$(cat /tmp/env-case-err)" "cleaning environ
executing: /mnt/bin/seq
   arg[0]= ‘/mnt/bin/seq’
   arg[1]= ‘2’"
check "env -v reports the exec exit status" "0" "$(LC_ALL=C.UTF-8 env -v -i /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -v reports the split
LC_ALL=C.UTF-8 env -v -i -S 'A=7 B=8' /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -v reports the split stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env -v reports the split stderr" "$(cat /tmp/env-case-err)" "split -S:  ‘A=7 B=8’
 into:    ‘A=7’
     &    ‘B=8’
cleaning environ
setenv:   A=7
setenv:   B=8
executing: /mnt/bin/seq
   arg[0]= ‘/mnt/bin/seq’
   arg[1]= ‘2’"
check "env -v reports the split exit status" "0" "$(LC_ALL=C.UTF-8 env -v -i -S 'A=7 B=8' /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -v reports the expansion
LC_ALL=C.UTF-8 env -v -i V=9 -S 'A=${V}' /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -v reports the expansion stderr" "$(cat /tmp/env-case-err)" "cleaning environ
setenv:   V=9
executing: -S
   arg[0]= ‘-S’
   arg[1]= ‘A=\${V}’
   arg[2]= ‘/mnt/bin/seq’
   arg[3]= ‘2’
env: ‘-S’: No such file or directory"
check "env -v reports the expansion exit status" "127" "$(LC_ALL=C.UTF-8 env -v -i V=9 -S 'A=${V}' /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env --debug long form
LC_ALL=C.UTF-8 env --debug -i A=7 /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env --debug long form stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env --debug long form stderr" "$(cat /tmp/env-case-err)" "cleaning environ
setenv:   A=7
executing: /mnt/bin/seq
   arg[0]= ‘/mnt/bin/seq’
   arg[1]= ‘2’"
check "env --debug long form exit status" "0" "$(LC_ALL=C.UTF-8 env --debug -i A=7 /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env lists blocked and ignored signals
LC_ALL=C.UTF-8 env --list-signal-handling --block-signal=INT --ignore-signal=TERM /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env lists blocked and ignored signals stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env lists blocked and ignored signals stderr" "$(cat /tmp/env-case-err)" "INT        ( 2): BLOCK
TERM       (15): IGNORE"
check "env lists blocked and ignored signals exit status" "0" "$(LC_ALL=C.UTF-8 env --list-signal-handling --block-signal=INT --ignore-signal=TERM /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env blocks a signal by number
LC_ALL=C.UTF-8 env --list-signal-handling --block-signal=2,10 /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env blocks a signal by number stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env blocks a signal by number stderr" "$(cat /tmp/env-case-err)" "INT        ( 2): BLOCK
USR1       (10): BLOCK"
check "env blocks a signal by number exit status" "0" "$(LC_ALL=C.UTF-8 env --list-signal-handling --block-signal=2,10 /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env blocks a spread of signals
LC_ALL=C.UTF-8 env --list-signal-handling --block-signal=INT,USR1,RTMIN+2,RTMAX /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env blocks a spread of signals stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env blocks a spread of signals stderr" "$(cat /tmp/env-case-err)" "INT        ( 2): BLOCK
USR1       (10): BLOCK
RTMIN+2    (36): BLOCK
RTMAX      (64): BLOCK"
check "env blocks a spread of signals exit status" "0" "$(LC_ALL=C.UTF-8 env --list-signal-handling --block-signal=INT,USR1,RTMIN+2,RTMAX /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env unblocks what --default-signal resets
LC_ALL=C.UTF-8 env --list-signal-handling --block-signal=INT --default-signal=INT /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env unblocks what --default-signal resets stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env unblocks what --default-signal resets exit status" "0" "$(LC_ALL=C.UTF-8 env --list-signal-handling --block-signal=INT --default-signal=INT /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env -v reports the mask change
LC_ALL=C.UTF-8 env -v --block-signal=INT /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env -v reports the mask change stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env -v reports the mask change stderr" "$(cat /tmp/env-case-err)" "signal INT (2) mask set to BLOCK
executing: /mnt/bin/seq
   arg[0]= ‘/mnt/bin/seq’
   arg[1]= ‘2’"
check "env -v reports the mask change exit status" "0" "$(LC_ALL=C.UTF-8 env -v --block-signal=INT /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

# env rejects an unknown signal
if LC_ALL=C.UTF-8 env --block-signal=NOPE /mnt/bin/seq 2 >/dev/null 2>&1; then fail "env rejects an unknown signal"; fi
check "env rejects an unknown signal message" "env: ‘NOPE’: invalid signal
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env --block-signal=NOPE /mnt/bin/seq 2 2>&1 >/dev/null)"
check "env rejects an unknown signal exit status" "125" "$(LC_ALL=C.UTF-8 env --block-signal=NOPE /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"

# env rejects a reserved signal number
if LC_ALL=C.UTF-8 env --block-signal=32 /mnt/bin/seq 2 >/dev/null 2>&1; then fail "env rejects a reserved signal number"; fi
check "env rejects a reserved signal number message" "env: ‘32’: invalid signal
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env --block-signal=32 /mnt/bin/seq 2 2>&1 >/dev/null)"
check "env rejects a reserved signal number exit status" "125" "$(LC_ALL=C.UTF-8 env --block-signal=32 /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"

# env rejects signal zero
if LC_ALL=C.UTF-8 env --block-signal=0 /mnt/bin/seq 2 >/dev/null 2>&1; then fail "env rejects signal zero"; fi
check "env rejects signal zero message" "env: ‘0’: invalid signal
Try 'env --help' for more information." "$(LC_ALL=C.UTF-8 env --block-signal=0 /mnt/bin/seq 2 2>&1 >/dev/null)"
check "env rejects signal zero exit status" "125" "$(LC_ALL=C.UTF-8 env --block-signal=0 /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"

# env accepts a real-time signal
LC_ALL=C.UTF-8 env --list-signal-handling --block-signal=RTMIN+1 /mnt/bin/seq 2 >/tmp/env-case-out 2>/tmp/env-case-err
check "env accepts a real-time signal stdout" "$(cat /tmp/env-case-out)" "1
2"
check "env accepts a real-time signal stderr" "$(cat /tmp/env-case-err)" "RTMIN+1    (35): BLOCK"
check "env accepts a real-time signal exit status" "0" "$(LC_ALL=C.UTF-8 env --list-signal-handling --block-signal=RTMIN+1 /mnt/bin/seq 2 >/dev/null 2>&1; echo $?)"
rm -f /tmp/env-case-out /tmp/env-case-err

echo "env ok"
exit 0
