#!/usr/bin/env bash
# expand(1) in the guest.
#
# Every expected value below is what GNU expand prints for the same input and
# command; they were generated by running the system tool rather than written
# by hand, because a hand-written expectation is how a case starts lying.
#
# Expectations that contain a tab are written with printf, so the stops are
# visible in the source instead of hiding as whitespace.
set -u

fail() { echo "FAIL: $*" >&2; exit 1; }
check() {
  if [ "$2" != "$3" ]; then
    printf 'FAIL: %s\n  expected: [%s]\n  actual:   [%s]\n' "$1" "$2" "$3" >&2
    exit 1
  fi
}

W=/tmp/expand-case
rm -rf "$W"
mkdir -p "$W"

printf 'a\tb\n\tc\nab\tc\td\n' > "$W/t1"
printf 'x\ty\n  \tz\n\t\n\t\t\n\n' > "$W/t2"
printf 'abc\b\b\td\ne\tf' > "$W/t3"
printf '\t \t\ta\n \t \t b\n' > "$W/t4"
printf '12345678901234567890\tx\n' > "$W/t5"
printf -- '-\tz\n' > "$W/t6"

# --- the default spacing --------------------------------------------------
check "expand default" "$(printf 'a       b\n        c\nab      c       d')" \
  "$(expand "$W/t1")"

# --- -i -------------------------------------------------------------------
# Only the leading blanks of a line are converted; the first tab after a
# non-blank is left alone.
check "expand -i" "$(printf 'a\tb\n        c\nab\tc\td')" "$(expand -i "$W/t1")"
check "expand -i long" "$(printf 'a\tb\n        c\nab\tc\td')" \
  "$(expand --initial "$W/t1")"

# -i counts a space as a blank, so this line is converted all the way through.
check "expand -i blank runs" "$(printf '                        a\n                 b')" \
  "$(expand -i "$W/t4")"

# --- -t -------------------------------------------------------------------
check "expand -t 4" "$(printf 'a   b\n    c\nab  c   d')" "$(expand -t 4 "$W/t1")"
check "expand -t 4 attached" "$(printf 'a   b\n    c\nab  c   d')" \
  "$(expand -t4 "$W/t1")"
check "expand -t 2" "$(printf 'a b\n  c\nab  c d')" "$(expand -t 2 "$W/t1")"
# A digit is an option of its own, with an optional argument: -4 is four
# columns and -4x would be the stop list "x".
check "expand -4" "$(printf 'a   b\n    c\nab  c   d')" "$(expand -4 "$W/t1")"
check "expand -t long" "$(printf 'a   b\n    c\nab  c   d')" \
  "$(expand --tabs=4 "$W/t1")"

# A list names the columns the tabs stop at; commas and blanks both separate.
check "expand -t 2,6" "$(printf 'a b\n  c\nab    c d')" \
  "$(expand -t 2,6 "$W/t1")"
check "expand -t '2 6'" "$(printf 'a b\n  c\nab    c d')" \
  "$(expand -t '2 6' "$W/t1")"

# A trailing /N keeps a spacing after the last stop; +N steps each further stop
# on by N. Both go in front of their number.
check "expand -t 2,4,/3" "$(printf 'a b\n  c\nab  c d')" \
  "$(expand -t 2,4,/3 "$W/t1")"
check "expand -t 2,+3" "$(printf 'a b\n  c\nab   c  d')" \
  "$(expand -t 2,+3 "$W/t1")"
check "expand -t /3" "$(printf 'a  b\n   c\nab c  d')" "$(expand -t /3 "$W/t1")"
check "expand -t +2" "$(printf 'a b\n  c\nab  c d')" "$(expand -t +2 "$W/t1")"

# --- operands -------------------------------------------------------------
check "expand two files" "$(printf 'a       b\n        c\nab      c       d\nx       y\n        z\n        \n                ')" \
  "$(expand "$W/t1" "$W/t2")"

# The operands are one character stream, so a first file with no trailing
# newline hands its column to the next one: "abc", two backspaces and "d" leave
# the column at 6, then "e" and the tab of the second file run from 6 to 8.
check "expand carries the column over" \
  "$(printf 'abc\b\b       d\ne       f-      z')" \
  "$(expand "$W/t3" "$W/t6")"

check "expand stdin" "$(printf 'a       b\n        c\nab      c       d')" \
  "$(expand < "$W/t1")"

# --- edge input -----------------------------------------------------------
check "expand blank runs" "$(printf '                        a\n                 b')" \
  "$(expand "$W/t4")"
# A tab well past the last stop still stops at the next multiple of eight.
check "expand wide line" '12345678901234567890    x' "$(expand "$W/t5")"

# A backspace is echoed and rewinds the column, and -i has already stopped by
# then so the tab after it survives.
check "expand backspace" "$(printf 'abc\b\b       d\ne       f')" \
  "$(expand "$W/t3")"
check "expand backspace with -i" "$(printf 'abc\b\b\td\ne\tf')" \
  "$(expand -i "$W/t3")"

# --- diagnostics ----------------------------------------------------------
if expand -t 0 "$W/t1" >/dev/null 2>&1; then
  fail "expand -t 0 succeeded"
fi
check "expand tab size zero" 'expand: tab size cannot be 0' \
  "$(expand -t 0 "$W/t1" 2>&1 >/dev/null)"

if expand -t 4,2 "$W/t1" >/dev/null 2>&1; then
  fail "expand -t 4,2 succeeded"
fi
check "expand stops must ascend" 'expand: tab sizes must be ascending' \
  "$(expand -t 4,2 "$W/t1" 2>&1 >/dev/null)"

# The bad character is quoted together with everything behind it.
if expand -t 4x,2 "$W/t1" >/dev/null 2>&1; then
  fail "expand -t 4x,2 succeeded"
fi
check "expand bad character" \
  'expand: tab size contains invalid character(s): ‘x,2’' \
  "$(expand -t 4x,2 "$W/t1" 2>&1 >/dev/null)"

# A specifier after a number is reported, and the scan carries on to report the
# invalid character behind it as well.
if expand -t 4+x "$W/t1" >/dev/null 2>&1; then
  fail "expand -t 4+x succeeded"
fi
check "expand misplaced specifier" "expand: '+' specifier not at start of number: ‘+x’
expand: tab size contains invalid character(s): ‘x’" \
  "$(expand -t 4+x "$W/t1" 2>&1 >/dev/null)"

if expand -t 99999999999999999999 "$W/t1" >/dev/null 2>&1; then
  fail "expand with a huge tab stop succeeded"
fi
check "expand tab stop too large" \
  'expand: tab stop is too large ‘99999999999999999999’' \
  "$(expand -t 99999999999999999999 "$W/t1" 2>&1 >/dev/null)"

if expand -t /3 -t /4 "$W/t1" >/dev/null 2>&1; then
  fail "expand with two slash specifiers succeeded"
fi
check "expand repeated slash" \
  "expand: '/' specifier only allowed with the last value" \
  "$(expand -t /3 -t /4 "$W/t1" 2>&1 >/dev/null)"

if expand -t /3 -t +1 "$W/t1" >/dev/null 2>&1; then
  fail "expand with slash and plus succeeded"
fi
check "expand slash and plus" \
  "expand: '/' specifier is mutually exclusive with '+'" \
  "$(expand -t /3 -t +1 "$W/t1" 2>&1 >/dev/null)"

if expand "$W/nope" >/dev/null 2>&1; then
  fail "expand of a missing file succeeded"
fi
check "expand missing file" "expand: $W/nope: No such file or directory" \
  "$(expand "$W/nope" 2>&1 >/dev/null)"

if expand "$W/t1" -t >/dev/null 2>&1; then
  fail "expand -t with no argument succeeded"
fi
check "expand -t needs an argument" "expand: option requires an argument -- 't'
Try 'expand --help' for more information." "$(expand "$W/t1" -t 2>&1 >/dev/null)"

if expand -Q "$W/t1" >/dev/null 2>&1; then
  fail "expand -Q succeeded"
fi
check "expand bad option" "expand: invalid option -- 'Q'
Try 'expand --help' for more information." "$(expand -Q "$W/t1" 2>&1 >/dev/null)"

rm -rf "$W"
echo "expand ok"
exit 0