#!/usr/bin/env bash
# nl(1) in the guest.
#
# Every expected value below is what GNU nl prints for the same input and
# command; they were generated by running the system tool, not written by hand,
# because a hand-written expectation is how a case starts lying.
#
# Expectations that contain a tab are written with printf rather than with a
# literal tab in a quoted string, so the column separator is visible in the
# source instead of hiding as whitespace.
set -u

fail() { echo "FAIL: $*" >&2; exit 1; }
check() {
  if [ "$2" != "$3" ]; then
    printf 'FAIL: %s\n  expected: [%s]\n  actual:   [%s]\n' "$1" "$2" "$3" >&2
    exit 1
  fi
}

W=/tmp/nl-case
rm -rf "$W"
mkdir -p "$W"

# The section delimiters are '\:' (footer), '\:\:' (body) and '\:\:\:' (header).
# "pages" is one logical page: header, body, footer. "tabs" has a run of blank
# lines for -l, and "words" has digits and spaces for the BRE styles.
printf '%s\n' 'H1' '\:' '' 'B1' 'B2' '\:\:' '' 'B3' '\:\:\:' 'F1' '' 'F2' > "$W/pages"
printf '%s\n' 'a' '' 'b' '' '' 'c' > "$W/tabs"
printf '%s\n' 'x y' 'p 12' 'r s' 'q 7' > "$W/words"
printf 'no trailing newline' > "$W/nonl"

# --- styles ---------------------------------------------------------------
check "nl -ba" "$(printf '     1\ta\n     2\t\n     3\tb\n     4\t\n     5\t\n     6\tc')" \
  "$(nl -ba "$W/tabs")"

# Only nonempty body lines are numbered by default, and every unnumbered line is
# still indented so the text lines up.
check "nl default on blanks" "$(printf '     1\ta\n       \n     2\tb\n       \n       \n     3\tc')" \
  "$(nl "$W/tabs")"

# A delimiter line is replaced by a bare newline, and the counter restarts in
# each new section.
check "nl default on a page" "$(printf '     1\tH1\n\n       \n       B1\n       B2\n\n       \n     1\tB3\n\n       F1\n       \n       F2')" \
  "$(nl "$W/pages")"

check "nl -bn" "$(printf '       H1\n\n       \n       B1\n       B2\n\n       \n       B3\n\n       F1\n       \n       F2')" \
  "$(nl -bn "$W/pages")"

check "nl -h a -f a" "$(printf '     1\tH1\n\n     1\t\n     2\tB1\n     3\tB2\n\n       \n     1\tB3\n\n     1\tF1\n     2\t\n     3\tF2')" \
  "$(nl -h a -f a "$W/pages")"

check "nl -h t" "$(printf '     1\tH1\n\n       \n       B1\n       B2\n\n       \n     1\tB3\n\n     1\tF1\n       \n     2\tF2')" \
  "$(nl -h t "$W/pages")"

check "nl -f t" "$(printf '     1\tH1\n\n       \n     1\tB1\n     2\tB2\n\n       \n     1\tB3\n\n       F1\n       \n       F2')" \
  "$(nl -f t "$W/pages")"

# -p keeps counting across sections instead of restarting.
check "nl -ba -p" "$(printf '     1\tH1\n\n       \n       B1\n       B2\n\n     2\t\n     3\tB3\n\n       F1\n       \n       F2')" \
  "$(nl -ba -p "$W/pages")"

# --- number placement -----------------------------------------------------
check "nl -v0" "$(printf '     0\tH1\n\n       \n       B1\n       B2\n\n     0\t\n     1\tB3\n\n       F1\n       \n       F2')" \
  "$(nl -ba -v0 "$W/pages")"

check "nl -v-3" "$(printf '    -3\ta\n    -2\t\n    -1\tb\n     0\t\n     1\t\n     2\tc')" \
  "$(nl -ba -v-3 "$W/tabs")"

check "nl -i2" "$(printf '     1\ta\n     3\t\n     5\tb\n     7\t\n     9\t\n    11\tc')" \
  "$(nl -ba -i2 "$W/tabs")"

check "nl -i-1" "$(printf '     1\ta\n     0\t\n    -1\tb\n    -2\t\n    -3\t\n    -4\tc')" \
  "$(nl -ba -i-1 "$W/tabs")"

# --- number shape ---------------------------------------------------------
check "nl -w3" "$(printf '  1\ta\n  2\t\n  3\tb\n  4\t\n  5\t\n  6\tc')" \
  "$(nl -ba -w3 "$W/tabs")"

check "nl -w1" "$(printf '1\ta\n2\t\n3\tb\n4\t\n5\t\n6\tc')" \
  "$(nl -ba -w1 "$W/tabs")"

check "nl -nln" "$(printf '1   \ta\n2   \t\n3   \tb\n4   \t\n5   \t\n6   \tc')" \
  "$(nl -ba -nln -w4 "$W/tabs")"

check "nl -nrz" "$(printf '0001\ta\n0002\t\n0003\tb\n0004\t\n0005\t\n0006\tc')" \
  "$(nl -ba -nrz -w4 "$W/tabs")"

# %0* keeps the sign in front of the zeros, so -2 is "-0002", not "00-02".
check "nl -nrz negative" "$(printf -- '-0002\ta\n-0001\t\n00000\tb\n00001\t\n00002\t\n00003\tc')" \
  "$(nl -ba -nrz -v-2 -w5 "$W/tabs")"

# --- separator ------------------------------------------------------------
check "nl -s." "$(printf '  1.a\n  2.\n  3.b\n  4.\n  5.\n  6.c')" \
  "$(nl -ba -w3 -s. "$W/tabs")"

# An empty separator needs the = form; a bare -s swallows the next argument.
check "nl --number-separator=" "$(printf '  1a\n  2\n  3b\n  4\n  5\n  6c')" \
  "$(nl -ba -w3 --number-separator= "$W/tabs")"

check "nl -s multi" "$(printf '  1 | a\n  2 | \n  3 | b\n  4 | \n  5 | \n  6 | c')" \
  "$(nl -ba -w3 -s' | ' "$W/tabs")"

# --- -l, grouping blank lines --------------------------------------------
# Only STYLE a looks at -l, and the group is charged on its last line.
check "nl -l2" "$(printf '     1\ta\n       \n     2\tb\n       \n     3\t\n     4\tc')" \
  "$(nl -ba -l2 "$W/tabs")"

check "nl -l3" "$(printf '     1\ta\n       \n     2\tb\n       \n       \n     3\tc')" \
  "$(nl -ba -l3 "$W/tabs")"

# STYLE t already skips blank lines, so -l changes nothing.
check "nl -bt -l2" "$(printf '     1\ta\n       \n     2\tb\n       \n       \n     3\tc')" \
  "$(nl -bt -l2 "$W/tabs")"

# --- -d, the section delimiter -------------------------------------------
# -d is a prefix, not a line: footer, body and header are that prefix repeated
# one, two and three times. A missing second character implies ':', so ':'
# builds on '::' and 'a' on 'a:' -- not on 'aa'.
printf '%s\n' 'x' '::' '::::' '::::::' 'aa' > "$W/dels"
check "nl -d: colon completed" "$(printf '     1\tx\n\n\n\n       aa')" "$(nl -ba -d: "$W/dels")"

printf '%s\n' 'x' 'a:' 'a:a:' 'a:a:a:' 'aa' > "$W/del2"
check "nl -d a:" "$(printf '     1\tx\n\n\n\n       aa')" "$(nl -ba -da: "$W/del2")"
check "nl -d a implies colon" "$(printf '     1\tx\n\n\n\n       aa')" "$(nl -ba -da "$W/del2")"

# Three or more characters is the GNU extension and is kept whole, so 'ab:'
# asks for 'ab:' and none of the 'ab' repeats match. Two characters is taken as
# given too, and then they do match.
printf '%s\n' 'x' 'ab' 'abab' 'ababab' 'abc' > "$W/del4"
check "nl -d ab: three chars" "$(printf '     1\tx\n     2\tab\n     3\tabab\n     4\tababab\n     5\tabc')" \
  "$(nl -ba -dab: "$W/del4")"
check "nl -d ab: two chars" "$(printf '     1\tx\n\n\n\n       abc')" \
  "$(nl -ba -dab "$W/del4")"

# An empty -d turns section matching off altogether.
check "nl --section-delimiter=off" "$(printf '     1\tH1\n     2\t\\:\n     3\t\n     4\tB1\n     5\tB2\n     6\t\\:\\:\n     7\t\n     8\tB3\n     9\t\\:\\:\\:\n    10\tF1\n    11\t\n    12\tF2')" \
  "$(nl -ba --section-delimiter= "$W/pages")"

# --- pBRE styles ----------------------------------------------------------
check "nl -bp digit" "$(printf '       x y\n     1\tp 12\n       r s\n     2\tq 7')" \
  "$(nl -bp'[0-9]' "$W/words")"

check "nl -bp no match" "$(printf '       x y\n       p 12\n       r s\n       q 7')" \
  "$(nl -bpzzz "$W/words")"

check "nl -bp anchored" "$(printf '       x y\n     1\tp 12\n       r s\n       q 7')" \
  "$(nl -bp'^p' "$W/words")"

check "nl -bp bracket" "$(printf '     1\tx y\n       p 12\n       r s\n       q 7')" \
  "$(nl -bp'[xy]' "$W/words")"

check "nl -bp alternation" "$(printf '     1\tx y\n       p 12\n       r s\n       q 7')" \
  "$(nl -bp'\(x\|y\) ' "$W/words")"

# A leading * is an operator with nothing to repeat, so it is literal here.
check "nl -bp leading star" "$(printf '     1\tx y\n     2\tp 12\n     3\tr s\n     4\tq 7')" \
  "$(nl -bp'q*' "$W/words")"

check "nl -bp dot" "$(printf '     1\tx y\n     2\tp 12\n     3\tr s\n     4\tq 7')" \
  "$(nl -bp'..' "$W/words")"

# --- inputs ---------------------------------------------------------------
check "nl long options" "$(printf '  1.a\n  2.\n  3.b\n  4.\n  5.\n  6.c')" \
  "$(nl --body-numbering=a --number-width=3 --number-separator=. "$W/tabs")"

# The counter carries over from one file to the next.
check "nl two files" "$(printf '     1\ta\n     2\t\n     3\tb\n     4\t\n     5\t\n     6\tc\n     7\tx y\n     8\tp 12\n     9\tr s\n    10\tq 7')" \
  "$(nl -ba "$W/tabs" "$W/words")"

check "nl stdin" "$(printf '     1\ta\n     2\t\n     3\tb\n     4\t\n     5\t\n     6\tc')" \
  "$(nl -ba < "$W/tabs")"

check "nl dash is stdin" "$(printf '     1\ta\n     2\t\n     3\tb\n     4\t\n     5\t\n     6\tc')" \
  "$(nl -ba - < "$W/tabs")"

check "nl no trailing newline" "$(printf '     1\tno trailing newline')" \
  "$(nl -ba "$W/nonl")"

# --- diagnostics ----------------------------------------------------------
# A bad STYLE is only a warning: the rest of the command line is still read and
# one Try line closes the run. The style value is quoted with typographic
# quotes, the Try line with plain ones, exactly as coreutils does.
if nl -bz "$W/tabs" >/dev/null 2>&1; then
  fail "nl -bz succeeded"
fi
check "nl -bz message" "nl: invalid body numbering style: ‘z’
Try 'nl --help' for more information." "$(nl -bz "$W/tabs" 2>&1 >/dev/null)"

# A bad numeric value stops at once, with no Try line.
if nl -wx "$W/tabs" >/dev/null 2>&1; then
  fail "nl -wx succeeded"
fi
if nl -w0 "$W/tabs" >/dev/null 2>&1; then
  fail "nl -w0 succeeded"
fi
if nl -l0 "$W/tabs" >/dev/null 2>&1; then
  fail "nl -l0 succeeded"
fi
if nl -vx "$W/tabs" >/dev/null 2>&1; then
  fail "nl -vx succeeded"
fi
if nl -nxx "$W/tabs" >/dev/null 2>&1; then
  fail "nl -nxx succeeded"
fi

# A pBRE that will not compile is fatal and gets no Try line either.
if nl -bp'[' "$W/tabs" >/dev/null 2>"$W/err"; then
  fail "nl with a bad regex succeeded"
fi
check "nl bad regex message" 'nl: Invalid regular expression' \
  "$(cat "$W/err")"

# Getopt's own diagnostics: the letter for a short option, the name for a long one.
if nl -Z >/dev/null 2>&1; then
  fail "nl -Z succeeded"
fi
check "nl bad short option" "nl: invalid option -- 'Z'
Try 'nl --help' for more information." "$(nl -Z 2>&1 >/dev/null)"

if nl --nonsense >/dev/null 2>&1; then
  fail "nl --nonsense succeeded"
fi
if nl -w >/dev/null 2>&1; then
  fail "nl -w with no argument succeeded"
fi
check "nl missing short argument" "nl: option requires an argument -- 'w'
Try 'nl --help' for more information." "$(nl -w 2>&1 >/dev/null)"
check "nl missing long argument" "nl: option '--number-width' requires an argument
Try 'nl --help' for more information." "$(nl --number-width 2>&1 >/dev/null)"

if nl "$W/absent" >/dev/null 2>&1; then
  fail "nl of a missing file succeeded"
fi
check "nl missing file message" "nl: $W/absent: No such file or directory" \
  "$(nl "$W/absent" 2>&1 >/dev/null)"

rm -rf "$W"
echo "nl ok"
exit 0