#!/usr/bin/env bash
# paste(1) in the guest.
#
# Every expected value below is what GNU paste prints for the same input and
# command; they were generated by running the system tool rather than written
# by hand, because a hand-written expectation is how a case starts lying.
#
# Expectations that contain a tab are written with printf, so the column
# separator is visible in the source instead of hiding as whitespace.
set -u

fail() { echo "FAIL: $*" >&2; exit 1; }
check() {
  if [ "$2" != "$3" ]; then
    printf 'FAIL: %s\n  expected: [%s]\n  actual:   [%s]\n' "$1" "$2" "$3" >&2
    exit 1
  fi
}

W=/tmp/paste-case
rm -rf "$W"
mkdir -p "$W"

printf '%s\n' 'a' 'b' 'c' > "$W/f"
printf '%s\n' 'x' 'y' 'z' > "$W/g"
printf '%s\n' '1' '2' > "$W/h"
printf '%s\n' 'p q' 'r s' > "$W/spaces"
: > "$W/empty"

# --- parallel, the default ------------------------------------------------
check "paste two files" "$(printf 'a\tx\nb\ty\nc\tz')" "$(paste "$W/f" "$W/g")"

check "paste three files" "$(printf 'a\tx\t1\nb\ty\t2\nc\tz\t')" \
  "$(paste "$W/f" "$W/g" "$W/h")"

# A file that runs out early leaves a hole where its column was, instead of
# shifting the rest of the row left.
check "paste short last file" "$(printf 'a\t1\nb\t2\nc\t')" \
  "$(paste "$W/f" "$W/h")"
check "paste short middle file" "$(printf 'a\t1\tx\nb\t2\ty\nc\t\tz')" \
  "$(paste "$W/f" "$W/h" "$W/g")"
check "paste empty file" "$(printf '\tx\n\ty\n\tz')" \
  "$(paste "$W/empty" "$W/g")"
check "paste empty file first" "$(printf '\ta\n\tb\n\tc')" \
  "$(paste "$W/empty" "$W/f")"

# Spaces inside a line are content, not a field break.
check "paste keeps spaces" "$(printf 'p q\tx\nr s\ty\n\tz')" \
  "$(paste "$W/spaces" "$W/g")"

# --- -d -------------------------------------------------------------------
check "paste one delimiter" "$(printf 'a,x\nb,y\nc,z')" \
  "$(paste -d, "$W/f" "$W/g")"

# The list is used cyclically and restarts on every row, so a two-character
# list over three files reads a, b on each row.
check "paste two delimiters" "$(printf 'axx\nbxy\ncxz')" \
  "$(paste -dxy "$W/f" "$W/g")"
check "paste delimiter cycles" "$(printf 'axxy1\nbxyy2\ncxzy')" \
  "$(paste -dxy "$W/f" "$W/g" "$W/h")"
check "paste three delimiters" "$(printf 'axxy1\nbxyy2\ncxzy')" \
  "$(paste -dxyz "$W/f" "$W/g" "$W/h")"
check "paste long delimiter option" "$(printf 'axx\nbxy\ncxz')" \
  "$(paste --delimiters=xy "$W/f" "$W/g")"

# An empty -d is rewritten to \0, which writes no delimiter at all.
check "paste empty delimiter" 'ax
by
cz' "$(paste -d '' "$W/f" "$W/g")"
check "paste tab escape is the default" "$(printf 'a\tx\nb\ty\nc\tz')" \
  "$(paste -d '\t' "$W/f" "$W/g")"

# --- -s -------------------------------------------------------------------
check "paste -s one file" "$(printf 'a\tb\tc')" "$(paste -s "$W/f")"
check "paste -s two files" "$(printf 'a\tb\tc\nx\ty\tz')" \
  "$(paste --serial "$W/f" "$W/g")"
check "paste -s three files" "$(printf 'a\tb\tc\nx\ty\tz\n1\t2')" \
  "$(paste -s "$W/f" "$W/g" "$W/h")"

# An empty file opened fine, so it still owes one row; a file that could not be
# opened owes nothing.
check "paste -s empty file" "$(printf 'a\tb\tc\n\nx\ty\tz')" \
  "$(paste -s "$W/f" "$W/empty" "$W/g")"
check "paste -s delimiters" 'axbyc' "$(paste -s -dxy "$W/f")"
check "paste -s no delimiter" 'abc' "$(paste -s -d '' "$W/f")"

# --- operands -------------------------------------------------------------
# With no operand at all the single column is just the input.
check "paste stdin" "$(printf 'a\nb\nc')" "$(paste < "$W/f")"
check "paste dash is stdin" "$(printf 'a\tx\nb\ty\nc\tz')" \
  "$(paste - "$W/g" < "$W/f")"
# Every - is the same stream, so the two columns take turns on it.
check "paste dash twice" "$(printf 'a\tb\nc\t')" "$(paste - - < "$W/f")"

# --- diagnostics ----------------------------------------------------------
# Parallel gives up at once, so the file that could be read is not printed.
if paste "$W/nope" "$W/g" >/dev/null 2>&1; then
  fail "paste with a missing file succeeded"
fi
check "paste missing file" "paste: $W/nope: No such file or directory" \
  "$(paste "$W/nope" "$W/g" 2>&1 >/dev/null)"

# Serial only warns and carries on, so the good file is still pasted.
if paste -s "$W/nope" "$W/g" >/dev/null 2>&1; then
  fail "paste -s with a missing file succeeded"
fi
check "paste -s missing file" "paste: $W/nope: No such file or directory" \
  "$(paste -s "$W/nope" "$W/g" 2>&1 >/dev/null)"
check "paste -s still pastes" "$(printf 'x\ty\tz')" \
  "$(paste -s "$W/nope" "$W/g" 2>/dev/null)"

if paste -Q "$W/f" >/dev/null 2>&1; then
  fail "paste -Q succeeded"
fi
check "paste bad option" "paste: invalid option -- 'Q'
Try 'paste --help' for more information." "$(paste -Q "$W/f" 2>&1 >/dev/null)"

if paste --nonsense "$W/f" >/dev/null 2>&1; then
  fail "paste --nonsense succeeded"
fi
if paste "$W/f" -d >/dev/null 2>&1; then
  fail "paste -d with no argument succeeded"
fi
check "paste missing -d argument" "paste: option requires an argument -- 'd'
Try 'paste --help' for more information." "$(paste "$W/f" -d 2>&1 >/dev/null)"
check "paste missing long argument" "paste: option '--delimiters' requires an argument
Try 'paste --help' for more information." "$(paste "$W/f" --delimiters 2>&1 >/dev/null)"

# The escape that starts nothing is fatal, and the message shows the list
# without doubling its backslashes.
if paste -d 'xy\' "$W/f" >/dev/null 2>&1; then
  fail "paste with a trailing backslash succeeded"
fi
check "paste trailing backslash" \
  'paste: delimiter list ends with an unescaped backslash: xy\' \
  "$(paste -d 'xy\' "$W/f" 2>&1 >/dev/null)"

rm -rf "$W"
echo "paste ok"
exit 0