#!/usr/bin/env bash
# unexpand(1) in the guest.
#
# Every expected value below is what GNU unexpand prints for the same input and
# command; they were generated by running the system tool rather than written by
# hand, because a hand-written expectation is how a case starts lying.
#
# Expectations that contain a tab are written with printf, so the folds are
# visible in the source instead of hiding as whitespace.
set -u

fail() { echo "FAIL: $*" >&2; exit 1; }
check() {
  if [ "$2" != "$3" ]; then
    printf 'FAIL: %s\n  expected: [%s]\n  actual:   [%s]\n' "$1" "$2" "$3" >&2
    exit 1
  fi
}

W=/tmp/unexpand-case
rm -rf "$W"
mkdir -p "$W"

printf '        a\n  b\n  \tc\n' > "$W/lead"
printf 'a        b\na \na       b\na   b\n' > "$W/mid"
printf '\t \t\ta\n \t \t b\n' > "$W/blanks"
printf 'a       \bd\nb       \bb\n' > "$W/bs"
printf '    a' > "$W/nonl"
printf 'q        r\n' > "$W/two"

# --- the default: leading blanks only --------------------------------------
check "unexpand leading blanks" "$(printf '\ta\n  b\n\tc')" "$(unexpand "$W/lead")"

# Once a line has a non-blank on it, the rest of the blanks are left alone.
check "unexpand stops at a non-blank" \
  "$(printf 'a        b\na \na       b\na   b')" "$(unexpand "$W/mid")"
check "unexpand --first-only" "$(printf 'a        b\na \na       b\na   b')" \
  "$(unexpand --first-only "$W/mid")"
# --first-only wins over -a whichever order they come in.
check "unexpand -a --first-only" "$(printf 'a        b\na \na       b\na   b')" \
  "$(unexpand -a --first-only "$W/mid")"

check "unexpand blank runs" "$(printf '\t\t\ta\n\t\t b')" "$(unexpand "$W/blanks")"
check "unexpand backspace" "$(printf 'a       \bd\nb       \bb')" \
  "$(unexpand "$W/bs")"
check "unexpand no newline" '    a' "$(unexpand "$W/nonl")"
check "unexpand two files" "$(printf '\ta\n  b\n\tc\nq        r')" \
  "$(unexpand "$W/lead" "$W/two")"
check "unexpand stdin" "$(printf '\ta\n  b\n\tc')" "$(unexpand < "$W/lead")"

# --- -a --------------------------------------------------------------------
# Eight blanks between two words become a tab and one blank: the blank that
# landed on the stop was the run's eighth, and the one before it cannot be
# folded into the tab that replaced it.
check "unexpand -a" "$(printf 'a\t b\na \na\tb\na   b')" "$(unexpand -a "$W/mid")"
check "unexpand --all" "$(printf 'a\t b\na \na\tb\na   b')" \
  "$(unexpand --all "$W/mid")"
check "unexpand -a blanks" "$(printf '\t\t\ta\n\t\t b')" \
  "$(unexpand -a "$W/blanks")"
check "unexpand -a backspace" "$(printf 'a\t\bd\nb\t\bb')" \
  "$(unexpand -a "$W/bs")"
check "unexpand -a no newline" '    a' "$(unexpand -a "$W/nonl")"

# --- -t --------------------------------------------------------------------
check "unexpand -t 2" "$(printf '\t\t\t\ta\n\tb\n\t\tc')" \
  "$(unexpand -t 2 "$W/lead")"
check "unexpand -t 2 attached" "$(printf '\t\t\t\ta\n\tb\n\t\tc')" \
  "$(unexpand -t2 "$W/lead")"
check "unexpand -t 4" "$(printf '\t\ta\n  b\n\tc')" "$(unexpand -t 4 "$W/lead")"
check "unexpand --tabs=4" "$(printf '\t\ta\n  b\n\tc')" \
  "$(unexpand --tabs=4 "$W/lead")"
check "unexpand -t 2,6" "$(printf '\t\t  a\n\tb\n\t\tc')" \
  "$(unexpand -t 2,6 "$W/lead")"
check "unexpand -t 2 -a" "$(printf 'a\t\t\t\t b\na \na\t\t\t\tb\na\t\tb')" \
  "$(unexpand -a -t 2 "$W/mid")"
# A digit is an option of its own, so -2 is the same as -t 2.
check "unexpand -2" "$(printf '\t\t\t\ta\n\tb\n\t\tc')" "$(unexpand -2 "$W/lead")"
# -t turns -a on by itself.
check "unexpand -t 8 implies -a" "$(printf 'a\t b\na \na\tb\na   b')" \
  "$(unexpand -t 8 "$W/mid")"
check "unexpand -t 2,4,/3" "$(printf 'a\t\t\t\tb\na \na\t\t\t  b\na\t\tb')" \
  "$(unexpand -a -t 2,4,/3 "$W/mid")"
check "unexpand -t 2,+3" "$(printf 'a\t\t\t b\na \na\t\t\tb\na\t  b')" \
  "$(unexpand -a -t 2,+3 "$W/mid")"

# --- diagnostics ----------------------------------------------------------
if unexpand -t 0 "$W/lead" >/dev/null 2>&1; then
  fail "unexpand -t 0 succeeded"
fi
check "unexpand tab size zero" 'unexpand: tab size cannot be 0' \
  "$(unexpand -t 0 "$W/lead" 2>&1 >/dev/null)"

if unexpand -t 4,2 "$W/lead" >/dev/null 2>&1; then
  fail "unexpand -t 4,2 succeeded"
fi
check "unexpand stops must ascend" 'unexpand: tab sizes must be ascending' \
  "$(unexpand -t 4,2 "$W/lead" 2>&1 >/dev/null)"

if unexpand -t 4x,2 "$W/lead" >/dev/null 2>&1; then
  fail "unexpand -t 4x,2 succeeded"
fi
check "unexpand bad character" \
  'unexpand: tab size contains invalid character(s): ‘x,2’' \
  "$(unexpand -t 4x,2 "$W/lead" 2>&1 >/dev/null)"

if unexpand -t 4+x "$W/lead" >/dev/null 2>&1; then
  fail "unexpand -t 4+x succeeded"
fi
check "unexpand misplaced specifier" "unexpand: '+' specifier not at start of number: ‘+x’
unexpand: tab size contains invalid character(s): ‘x’" \
  "$(unexpand -t 4+x "$W/lead" 2>&1 >/dev/null)"

if unexpand -t 99999999999999999999 "$W/lead" >/dev/null 2>&1; then
  fail "unexpand with a huge tab stop succeeded"
fi
check "unexpand tab stop too large" \
  'unexpand: tab stop is too large ‘99999999999999999999’' \
  "$(unexpand -t 99999999999999999999 "$W/lead" 2>&1 >/dev/null)"

if unexpand -t /3 -t /4 "$W/lead" >/dev/null 2>&1; then
  fail "unexpand with two slash specifiers succeeded"
fi
check "unexpand repeated slash" \
  "unexpand: '/' specifier only allowed with the last value" \
  "$(unexpand -t /3 -t /4 "$W/lead" 2>&1 >/dev/null)"

if unexpand -t /3 -t +1 "$W/lead" >/dev/null 2>&1; then
  fail "unexpand with slash and plus succeeded"
fi
check "unexpand slash and plus" \
  "unexpand: '/' specifier is mutually exclusive with '+'" \
  "$(unexpand -t /3 -t +1 "$W/lead" 2>&1 >/dev/null)"

if unexpand "$W/nope" >/dev/null 2>&1; then
  fail "unexpand of a missing file succeeded"
fi
check "unexpand missing file" "unexpand: $W/nope: No such file or directory" \
  "$(unexpand "$W/nope" 2>&1 >/dev/null)"

if unexpand "$W/lead" -t >/dev/null 2>&1; then
  fail "unexpand -t with no argument succeeded"
fi
check "unexpand -t needs an argument" "unexpand: option requires an argument -- 't'
Try 'unexpand --help' for more information." \
  "$(unexpand "$W/lead" -t 2>&1 >/dev/null)"

if unexpand -Q "$W/lead" >/dev/null 2>&1; then
  fail "unexpand -Q succeeded"
fi
check "unexpand bad option" "unexpand: invalid option -- 'Q'
Try 'unexpand --help' for more information." \
  "$(unexpand -Q "$W/lead" 2>&1 >/dev/null)"

rm -rf "$W"
echo "unexpand ok"
exit 0