#!/usr/bin/env bash
# The cases shared by the whole `*sum` family. TOOL and SYS are set by each
# entry script, so the same list runs against every tool.
#
# The fixture checksum files are written as literals. They are what the system
# tool produces for the fixture files, so both sides see the same input; the
# comparison is the tool's behaviour, not the digest itself.

F='printf "hello world\n" > a.txt; printf "second file\n" > b.txt; : > empty.txt'

run_case "single file"        "$F" "$TOOL a.txt"
run_case "two files"          "$F" "$TOOL a.txt b.txt"
run_case "empty file"         "$F" "$TOOL empty.txt"
run_case "missing file"       "$F" "$TOOL a.txt missing.txt"
run_case "directory"          "$F; mkdir sub" "$TOOL sub"
run_case "standard input"     "$F" 'printf "hello world\n" | '"$TOOL"
run_case "dash for stdin"     "$F" 'printf "hello world\n" | '"$TOOL"' -'
run_case "two files one bad"  "$F" "$TOOL a.txt missing.txt b.txt"

if [ "$TOOL" != sum ]; then
  run_case "binary marker"    "$F" "$TOOL -b a.txt"
  run_case "text mode"        "$F" "$TOOL -t a.txt"
  run_case "binary then text" "$F" "$TOOL -b -t a.txt"
  run_case "text then binary" "$F" "$TOOL -t -b a.txt"
  run_case "tagged output"    "$F" "$TOOL --tag a.txt"
  run_case "zero terminated"  "$F" "$TOOL -z a.txt"
  run_case "name with newline" "$F" 'printf "hello world\n" > $'"'"'nl\nname.txt'"'"'; '"$TOOL"' $'"'"'nl\nname.txt'"'"''
  run_case "name with space"   "$F" 'printf "hello world\n" > "a b.txt"; '"$TOOL"' "a b.txt"'
  run_case "name with quote"   "$F" 'printf "hello world\n" > "q.txt"; '"$TOOL"' "q.txt"'
  run_case "empty name"        "$F" "$TOOL ''"
  run_case "option after file" "$F" "$TOOL a.txt --tag"
  run_case "separator"         "$F" "$TOOL -- a.txt"
  run_case "invalid option"    "$F" "$TOOL -x a.txt"
  run_case "unknown long"      "$F" "$TOOL --foo a.txt"
  run_case "ambiguous option"  "$F" "$TOOL --st a.txt"
  run_case "missing argument"  "$F" "$TOOL --tag -- a.txt"
  run_case "check-only option" "$F" "$TOOL --status a.txt"
  run_case "quiet alone"       "$F" "$TOOL --quiet a.txt"
  run_case "warn alone"        "$F" "$TOOL --warn a.txt"
  run_case "strict alone"      "$F" "$TOOL --strict a.txt"

  # Check mode. Each list is one of: all good, all bad, mixed, empty, unreadable.
  # The list is generated by the system tool, so both sides see the same fixture
  # and what is being compared is the tool's behaviour on it, not the digest.
  GOOD="$SYS a.txt > list.txt"
  run_case "check good"        "$F; $GOOD" "$TOOL -c list.txt"
  run_case "check warn"        "$F; $GOOD; printf 'notahex  a.txt\n' >> list.txt" "$TOOL -c --warn list.txt"
  run_case "check strict"      "$F; $GOOD; printf 'notahex  a.txt\n' >> list.txt" "$TOOL -c --strict list.txt"
  run_case "check quiet"       "$F; $GOOD" "$TOOL -c --quiet list.txt"
  run_case "check status"      "$F; $GOOD" "$TOOL -c --status list.txt"
  run_case "check status bad"  "$F; printf 'deadbeef  a.txt\n' > list.txt" "$TOOL -c --status list.txt"
  run_case "check empty list"  "$F; : > list.txt" "$TOOL -c list.txt"
  run_case "check blank lines" "$F; $GOOD; printf '\n\n' >> list.txt" "$TOOL -c list.txt"
  run_case "check no newline"  "$F; $GOOD" "$TOOL -c list.txt"
  run_case "check binary flag" "$F; printf 'b1946ac92492d2347c6235b4d2611184 *a.txt\n' > list.txt" "$TOOL -c list.txt"
  run_case "check escaped name" "$F; printf 'hello world\n' > $'"'"'nl\nname.txt'"'"'; printf '\\b1946ac92492d2347c6235b4d2611184  nl\\nname.txt\n' > list.txt" "$TOOL -c list.txt"
  run_case "check missing file" "$F; $GOOD; printf 'deadbeef  gone.txt\n' >> list.txt" "$TOOL -c list.txt"
  run_case "check ignore missing" "$F; printf 'deadbeef  gone.txt\n' > list.txt" "$TOOL -c --ignore-missing list.txt"
  run_case "check ignore missing status" "$F; printf 'deadbeef  gone.txt\n' > list.txt" "$TOOL -c --ignore-missing --status list.txt"
  run_case "check two lists"   "$F; $GOOD" "$TOOL -c list.txt list.txt"
  run_case "check tagged form"  "$F; printf 'hello world\n' > a.txt; printf 'MD5 (a.txt) = b1946ac92492d2347c6235b4d2611184\n' > list.txt" "$TOOL -c list.txt"
  run_case "check wrong tag"    "$F; printf 'hello world\n' > a.txt; printf 'md5 (a.txt) = b1946ac92492d2347c6235b4d2611184\n' > list.txt" "$TOOL -c list.txt"
  run_case "check tag conflict" "$F; $GOOD" "$TOOL --tag --check list.txt"
  run_case "check zero conflict" "$F; $GOOD" "$TOOL -c -z list.txt"
  run_case "check stdin"        "$F; $GOOD" "$TOOL -c < list.txt"

  run_case "posixly correct"    "$F; $GOOD" "POSIXLY_CORRECT=1 $TOOL a.txt --check list.txt"
fi

if [ "$TOOL" = cksum ] || [ "$TOOL" = b2sum ]; then
  run_case "length 256"        "$F" "$TOOL -l 256 a.txt"
  run_case "length not multiple of 8" "$F" "$TOOL -l 100 a.txt"
  run_case "length not a number" "$F" "$TOOL -l abc a.txt"
  run_case "length too big"    "$F" "$TOOL -l 1000 a.txt"
  run_case "length attached"   "$F" "$TOOL -l256 a.txt"
  run_case "length empty"      "$F" "$TOOL -l '' a.txt"
fi

if [ "$TOOL" = cksum ]; then
  for a in bsd sysv crc md5 sha1 sha224 sha256 sha384 sha512 sm3 blake2b; do
    run_case "algorithm $a" "$F" "$TOOL -a $a a.txt"
  done
  run_case "algorithm unknown"  "$F" "$TOOL -a nope a.txt"
  run_case "base64 output"      "$F" "$TOOL --base64 a.txt"
  run_case "raw output"         "$F" "$TOOL --raw a.txt"
  run_case "untagged output"    "$F" "$TOOL --untagged a.txt"
  run_case "check numeric"      "$F" "$TOOL -c -a crc list.txt"
  run_case "check with algorithm" "$F; printf 'hello world\n' > a.txt; printf 'MD5 (a.txt) = b1946ac92492d2347c6235b4d2611184\n' > list.txt" "$TOOL -c -a md5 list.txt"
  run_case "check blake2b tagged" "$F; printf 'hello world\n' > a.txt; printf 'BLAKE2b (a.txt) = 9f8e7d6c5b4a39281706f5e4d3c2b1a09f8e7d6c5b4a39281706f5e4d3c2b1a09f8e7d6c5b4a39281706f5e4d3c2b1a0\n' > list.txt" "$TOOL -c -a blake2b list.txt"
fi

if [ "$TOOL" = sum ]; then
  run_case "bsd default"        "$F" "$TOOL a.txt"
  run_case "sysv"               "$F" "$TOOL -s a.txt"
  run_case "bsd explicit"       "$F" "$TOOL -r a.txt"
  run_case "last wins"          "$F" "$TOOL -r -s a.txt"
  run_case "sysv long"          "$F" "$TOOL --sysv a.txt"
  run_case "bsd long rejected"  "$F" "$TOOL --bsd a.txt"
  run_case "check rejected"     "$F" "$TOOL -c a.txt"
  run_case "binary rejected"    "$F" "$TOOL -b a.txt"
  # The fixture is built with the system head, not the tool under test: a case must
  # not be generated by the thing it is measuring.
  run_case "big file blocks" "$F; /usr/bin/head -c 2000 /dev/zero > big.bin; /usr/bin/head -c 1025 /dev/zero > just.bin" "$TOOL big.bin just.bin"
fi
